name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24
      - uses: actions/checkout@v4.2.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.2
        with:
          version: v1.50

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24
      - name: Test
        run: go test -v ./...
